<a href="https://colab.research.google.com/github/Jyothi-Swaroop5/CodeAlpha/blob/main/Week2/Numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [121]:
import numpy
a=numpy.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [122]:
import numpy as np
a=np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [123]:
from numpy import*
a=numpy.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [124]:
#array()
#linspace()
#arange()
#zeros()
#ones()
#eye()
#empty()

In [125]:
import numpy as np

In [126]:
a=array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [127]:
a=linspace(1,5,2)
a

array([1., 5.])

In [128]:
a=np.arange(10)
b=np.arange(5,10)
c=np.arange(10,10,-1)
a,b,c

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([5, 6, 7, 8, 9]),
 array([], dtype=int64))

In [129]:
z=np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [130]:
o=np.ones((4,5))
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [131]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [132]:
a=np.empty([3,2])
a

array([[4.9e-324, 9.9e-324],
       [1.5e-323, 2.0e-323],
       [2.5e-323, 3.0e-323]])

In [133]:
k=np.array([1,2,3,4,5])
k=k+5
k

array([ 6,  7,  8,  9, 10])

In [134]:
#  1 dimensional array
a=np.array([1,2,3,4,5])
print(a[0])
print(a[-1])
#  2 dimensional array
b=np.array([[2,3,4,9],[4,3,5,6]])
print(b[0,0])
print(b[-1,-1])
#  2 dimensional array
c=a=np.array([[[2,3,4,9],[4,3,5,6]],[[4,6,4,3],[4,7,8,3]]])
print(c[0,1,2])
print(c[-1,-2,-3])

1
5
2
6
5
6


In [135]:
a=np.array([[1,2,3,4,1],[4,5,6,7,2]],dtype=np.int64)
b=np.array([1,2,3,4,5,6,7,8])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.itemsize)
print(a.data)
print(a.dtype)
print(a.strides)
print(a.reshape(2,5))
print(np.resize(a,(5,2)))
print(np.reshape(b,(2,2,2)))


2
(2, 5)
10
8
int64
(40, 8)
[[1 2 3 4 1]
 [4 5 6 7 2]]
[[1 2]
 [3 4]
 [1 4]
 [5 6]
 [7 2]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [136]:
#Joins in array
#1.concatenate()
#2.hstack()
#3.vstack()

In [137]:
#concatenate()
a=np.array([2,3,4,9])
b=np.array([4,3,5,6])
c=np.concatenate([a,b])
print(c)
a=np.array([[2,3,4,9],[4,3,5,6]])
b=np.array([[4,6,4,3],[4,7,8,3]])
c=np.concatenate([a,b])
c

[2 3 4 9 4 3 5 6]


array([[2, 3, 4, 9],
       [4, 3, 5, 6],
       [4, 6, 4, 3],
       [4, 7, 8, 3]])

In [138]:
#axis=0,column wise
a=np.array([[2,3,4,9],[4,3,5,6]])
b=np.array([[4,6,4,3],[4,7,8,3]])
c=np.concatenate([a,b],axis=0)
print(c)
#axis=1,row wise
a=np.array([[2,3,4,9],[4,3,5,6]])
b=np.array([[4,6,4,3],[4,7,8,3]])
c=np.concatenate([a,b],axis=1)
print(c)


[[2 3 4 9]
 [4 3 5 6]
 [4 6 4 3]
 [4 7 8 3]]
[[2 3 4 9 4 6 4 3]
 [4 3 5 6 4 7 8 3]]


In [139]:
#vstack()
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.vstack((a,b))
print(c)
#hstack()
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.hstack([a,b])
print(c)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [140]:
# working with matrix
a=np.array([[1,2,3],[4,5,6],[6,7,8]])
b=np.array([[9,8,7],[6,5,4],[3,2,1]])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))

[[10 10 10]
 [10 10 10]
 [ 9  9  9]]
[[-8 -6 -4]
 [-2  0  2]
 [ 3  5  7]]
[[ 9 16 21]
 [24 25 24]
 [18 14  8]]


In [141]:
a=np.array([[1,2,3],[4,5,6],[6,7,8]])
b=np.array([[9,8,7],[6,5,4],[3,2,1]])
print(np.r_[(a,b)])   #row_wise
print(np.c_[(a,b)])   #column_wise

[[1 2 3]
 [4 5 6]
 [6 7 8]
 [9 8 7]
 [6 5 4]
 [3 2 1]]
[[1 2 3 9 8 7]
 [4 5 6 6 5 4]
 [6 7 8 3 2 1]]


In [142]:
# it converts a multi‑dimensional array into a 1‑D array.
a=np.array([[1,2,3],[4,5,6],[6,7,8]])
b=np.array([[[9,8,7],[6,5,4],[3,2,1]]])
print(np.reshape(a,-1))
print(b.flatten())

[1 2 3 4 5 6 6 7 8]
[9 8 7 6 5 4 3 2 1]


In [143]:
#Expanding Array
array=np.array([[2,5,3],[8,3,9],[1,4,7]])
print(np.expand_dims(array,axis=(0,1)))

[[[[2 5 3]
   [8 3 9]
   [1 4 7]]]]


In [144]:
# squeeszing
a=np.array([[[1],[2],[3]]])
print(a)
print(a.shape)
b=np.squeeze(a,axis=0)
print(a)
print(a.shape)


[[[1]
  [2]
  [3]]]
(1, 3, 1)
[[[1]
  [2]
  [3]]]
(1, 3, 1)


In [145]:
array=np.array([[2,5,3],[8,3,9],[1,4,7]])
print(np.sort(array))
print(np.sort(array,kind='quicksort'))

[[2 3 5]
 [3 8 9]
 [1 4 7]]
[[2 3 5]
 [3 8 9]
 [1 4 7]]
